/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Jendela;

import java.awt.HeadlessException;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class Form2 extends javax.swing.JFrame {

       
    
    /**
     * Creates new form Form2
     */
    public Form2() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        list1 = new java.awt.List();
        panel1 = new java.awt.Panel();
        panel2 = new java.awt.Panel();
        jPanel1 = new javax.swing.JPanel();
        btnSubmit = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtSeri = new javax.swing.JTextField();
        txtnomorRangka = new javax.swing.JTextField();
        txtPlat = new javax.swing.JComboBox<>();
        comboProvinsi = new javax.swing.JComboBox<>();
        Plat = new javax.swing.JLabel();
        NomorPlat = new javax.swing.JLabel();
        NomorSeri = new javax.swing.JLabel();
        NomorRangka = new javax.swing.JLabel();
        Provinis = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        pkbTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        swdklljTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        adm1Txt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        adm2Txt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jumlahTxt = new javax.swing.JTextField();
        jenisKendaraan = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtNomorPlat = new javax.swing.JTextField();
        BtnHapus = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 51));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSubmit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 92, 31));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setText(":");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 60, -1, -1));

        txtSeri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSeriActionPerformed(evt);
            }
        });
        txtSeri.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSeriKeyTyped(evt);
            }
        });
        jPanel1.add(txtSeri, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 181, -1));

        txtnomorRangka.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnomorRangkaKeyTyped(evt);
            }
        });
        jPanel1.add(txtnomorRangka, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 182, -1));

        txtPlat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "AA", "AD", "K", "R", "G", "H", "AB", "D", "F", "E", "Z", "T", "A", "B", "AG", "AE", "L", "M", "N", "S", "W", "P", "DK", "ED", "EA", "EB", "DH", "DR", "KU", "KT", "DA", "KB", "KH", "DC", "DD", "DN", "DT", "DL", "DM", "DB", "BA", "BB", "BD", "BE", "BG", "BH", "BK", "BL", "BM", "BN", "BP", "DE", "DG", "PA", "PB", " " }));
        txtPlat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlatActionPerformed(evt);
            }
        });
        jPanel1.add(txtPlat, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 57, 181, -1));

        comboProvinsi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Aceh", "Bali", "Bangka Belitung", "Banten", "Bengkulu", "DI Yogyakarta", "DKI Jakarta", "Gorontalo", "Jambi", "Jawa Barat", "Jawa Tengah", "Jawa Timur", "Kepulauan Riau", "Kalimantan Timur", "Kalimantan Utara", "Kalimantan Barat", "Kalimantan Selatan", "Kepulauan Bangka Belitung", "Lampung", "Maluku", "Maluku Utara", "Nusa Tenggara Barat", "Nusa Tenggara Timur", "Papua", "Papua Barat", "Riau", "Sulawesi Barat", "Sulawesi Tengah", "Sulawesi Utara", "Sulawesi Tenggara", "Sulawesi Selatan", "Sumatera Utara", "Sumatera Barat", "Sumatera Selatan", " ", " " }));
        jPanel1.add(comboProvinsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 182, -1));

        Plat.setBackground(new java.awt.Color(255, 255, 255));
        Plat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Plat.setText("Plat ");
        jPanel1.add(Plat, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        NomorPlat.setBackground(new java.awt.Color(255, 255, 255));
        NomorPlat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NomorPlat.setText("Nomor Plat");
        jPanel1.add(NomorPlat, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        NomorSeri.setBackground(new java.awt.Color(255, 255, 255));
        NomorSeri.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NomorSeri.setText("Nomor Seri");
        jPanel1.add(NomorSeri, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 69, -1));

        NomorRangka.setBackground(new java.awt.Color(255, 255, 255));
        NomorRangka.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NomorRangka.setText("Nomor Rangka");
        jPanel1.add(NomorRangka, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        Provinis.setBackground(new java.awt.Color(255, 255, 255));
        Provinis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Provinis.setText("Provinsi");
        jPanel1.add(Provinis, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 57, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(":");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setText(":");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setText(":");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("CEK PAJAK ANDA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setText(":");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("Kembali");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 590, 90, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(pkbTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 21, 166, -1));

        jLabel2.setText("PKB ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 24, -1, -1));
        jPanel2.add(swdklljTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 49, 166, -1));

        jLabel3.setText("SWDKLLJ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 52, -1, -1));

        jLabel4.setText("BIAYA ADM.STNK");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 77, -1, -1));
        jPanel2.add(adm1Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 77, 166, -1));

        jLabel5.setText("BIAYA ADM.TNKB");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 108, -1, -1));
        jPanel2.add(adm2Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 105, 165, -1));

        jLabel12.setText("TOTAL");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 162, -1, -1));
        jPanel2.add(jumlahTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 159, 214, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 490, 210));

        jenisKendaraan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "RODA DUA", "RODA EMPAT", " ", " " }));
        jPanel1.add(jenisKendaraan, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 182, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Jenis Kendaraan");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setText(":");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 7, -1));

        jLabel15.setText("(Masukkan 5 digit akhir nomor rangka*)");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 220, 20));

        jLabel16.setText("(Masukkan 5 digit akhir nomor seri*)");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 200, 20));

        jPanel3.setBackground(new java.awt.Color(255, 255, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Penting! :Informasi diatas dapat dilihat dari STNK yang anda dimiliki.");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, 380, 40));
        jPanel1.add(txtNomorPlat, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 180, -1));

        BtnHapus.setText("Hapus");
        BtnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHapusActionPerformed(evt);
            }
        });
        jPanel1.add(BtnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new Form1().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtPlatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlatActionPerformed

    private void txtnomorRangkaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomorRangkaKeyTyped
        // TODO add your handling code here:
        String input=txtnomorRangka.getText();
        if(input.length()>4){
            JOptionPane.showMessageDialog(rootPane,"jumlah input melebihi batas");
            txtnomorRangka.setText("");
        }
    }//GEN-LAST:event_txtnomorRangkaKeyTyped

    private void txtSeriKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSeriKeyTyped
        String input=txtSeri.getText();
        if(input.length()>4){
            JOptionPane.showMessageDialog(rootPane,"jumlah input melebihi batas");
            txtSeri.setText("");
        }
    }//GEN-LAST:event_txtSeriKeyTyped

    private void txtSeriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSeriActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtSeriActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        int pkb,swdkllj,adm1,adm2;
        String PKB,SWDKLLJ,biaya1,biaya2;
        switch (jenisKendaraan.getSelectedIndex()){
            case 0 :
            pkb = 0;
            swdkllj = 0;
            adm1 = 0;
            adm2 = 0;
            break;
            case 1 :
            pkb = 264000;
            swdkllj = 35000;
            adm1 = 50000;
            adm2 = 0;
            break;
            default :
            pkb = 1900000;
            swdkllj = 50000;
            adm1 = 0;
            adm2 = 100000;
            break;
        }
        {
        int jumlah = pkb + swdkllj + adm1 + adm2;
        PKB = Integer.toString(pkb);
        SWDKLLJ = Integer.toString(swdkllj);
        biaya1 = Integer.toString(adm1);
        biaya2 = Integer.toString(adm2);
        String JUMLAH = Integer.toString(jumlah);
        pkbTxt.setText(PKB);
        swdklljTxt.setText(SWDKLLJ);
        adm1Txt.setText(biaya1);
        adm2Txt.setText(biaya2);
        jumlahTxt.setText(JUMLAH);
        }

    }//GEN-LAST:event_btnSubmitActionPerformed

    private void BtnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHapusActionPerformed
        // TODO add your handling code here:
        txtPlat.setSelectedItem(null);
        txtNomorPlat.setText("");
        txtSeri.setText("");
        txtnomorRangka.setText("");
        comboProvinsi.setSelectedItem(null);
        jenisKendaraan.setSelectedItem(null);
    }//GEN-LAST:event_BtnHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnHapus;
    private javax.swing.JLabel NomorPlat;
    private javax.swing.JLabel NomorRangka;
    private javax.swing.JLabel NomorSeri;
    private javax.swing.JLabel Plat;
    private javax.swing.JLabel Provinis;
    private javax.swing.JTextField adm1Txt;
    private javax.swing.JTextField adm2Txt;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> comboProvinsi;
    private javax.swing.JButton jButton2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox<String> jenisKendaraan;
    private javax.swing.JTextField jumlahTxt;
    private java.awt.List list1;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private javax.swing.JTextField pkbTxt;
    private javax.swing.JTextField swdklljTxt;
    private javax.swing.JTextField txtNomorPlat;
    private javax.swing.JComboBox<String> txtPlat;
    private javax.swing.JTextField txtSeri;
    private javax.swing.JTextField txtnomorRangka;
    // End of variables declaration//GEN-END:variables

    private static class hasil {

        public hasil() {
        }
    }

    private static class Hasil {

        public Hasil() {
        }
    }
}
